services:

  rustygate:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: ghcr.io/3loc/rustygate:latest
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8080
      - BIND_ADDRESS=0.0.0.0
      - RUST_LOG=debug
      - SSE_CHANNEL_CAPACITY=100
      - SSE_KEEPALIVE_INTERVAL=15
      - SSE_BUFFER_CAPACITY=1024
      - RATE_LIMIT=1
      - RATE_LIMIT_BURST=3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  tests:
    build:
      context: .
      dockerfile: tests/python/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: ghcr.io/3loc/rustygate-test:latest
    environment:
      - RUSTYGATE_ENDPOINT=http://rustygate:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      rustygate:
        condition: service_healthy 
