---
name: Release Binaries

"on":
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: rustygate-linux-amd64

          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: rustygate-linux-arm64

          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rustygate-darwin-amd64

          - os-name: macOS-aarch64
            runs-on: macos-latest
            target: aarch64-apple-darwin
            artifact_name: rustygate-darwin-arm64

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev musl-tools

      - name: Build with Cross (Linux)
        if: runner.os == 'Linux'
        uses: houseabsolute/actions-rust-cross@v0.0.15
        with:
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
          env: |
            OPENSSL_STATIC=1
            PKG_CONFIG_ALLOW_CROSS=1
            OPENSSL_DIR=/usr
            PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
            PKG_CONFIG_SYSROOT_DIR=/
            RUSTFLAGS="-C target-feature=+crt-static"

      - name: Install Rust (macOS)
        if: runner.os == 'macOS'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Prepare artifact
        run: |
          cp target/${{ matrix.platform.target }}/release/main ${{ matrix.platform.artifact_name }}

      - name: Generate SHA256
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sha256sum ${{ matrix.platform.artifact_name }} > ${{ matrix.platform.artifact_name }}.sha256
          else
            shasum -a 256 ${{ matrix.platform.artifact_name }} > ${{ matrix.platform.artifact_name }}.sha256
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact_name }}
          path: |
            ${{ matrix.platform.artifact_name }}
            ${{ matrix.platform.artifact_name }}.sha256

  create-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/rustygate-*
          generate_release_notes: true
